import type { Metadata } from "next";
import "./globals.css";
import { Inter as FontSans } from "next/font/google";
import { cn } from "@/lib/utils";
import Link from "next/link";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <div>
          <header className="bg-blue-500 text-white p-4">
            <nav className="container mx-auto flex justify-between">
              <Link href="/posts">My Blog</Link>
              <div>
                <Link href="/posts">Blog</Link>
                <Link href="/posts/create">Create Post</Link>
              </div>
            </nav>
          </header>
          <main className="container mx-auto p-4">{children}</main>
          <footer className="bg-blue-500 text-white p-4 text-center">
            © 2024 My Blog
          </footer>
        </div>
      </body>
    </html>
  );
}
